spring:
  datasource:
    auto-commit: false
    url: ${DB_HOST}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      connection:
        provider_disables_autocommit: true
    show-sql: true