spring:
  profiles:
    active: prod
#  datasource:
#    url: jdbc:mysql://localhost:3306/samurai_cars
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: catolica
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true